wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry>", views.entry_page, name="entry"),
    path("wiki/<str:entry>", views.entry_page, name="entry"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("random/", views.random_page, name="random"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import random
from markdown2 import Markdown

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def entry_page(request, entry:str):
    mk = Markdown()
    for en in util.list_entries():
        if entry.upper() == en.upper():
            return render(
                request,
                "encyclopedia/entry.html",
                {"entry_name": en, "entry": mk.convert(util.get_entry(en))},
            )
    return render(
        request,
        "encyclopedia/error.html",
        {"error": 404, "error_message": f"The title '{entry}' does not exist."},
    )


def search(request):
    entry = request.GET.get("q")
    entries = util.list_entries()
    result = []
    if entry:
        for en in entries:
            if entry.upper() == en.upper():
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[entry]))
            if entry.upper() in en.upper():
                result.append(en)
    if not result:
        return render(
            request,
            "encyclopedia/error.html",
            {"error": 404, "error_message": f"The title '{entry}' wasn't found."},
        )
    return render(request, "encyclopedia/search.html", {"entry": result})


def create(request):
    if request.method == "POST":
        title = request.POST.get("title")
        text = request.POST.get("textarea").encode("utf-8")
        entries = util.list_entries()
        exists = [en for en in entries if title.upper() == en.upper()]
        if not exists:
            if title and text:
                util.save_entry(title, text)
                return HttpResponseRedirect(reverse("encyclopedia:index"))
            else:
                return render(
                    request,
                    "encyclopedia/error.html",
                    {
                        "error": 400,
                        "error_message": "Must provide title and Markdown text.",
                    },
                )
        else:
            return render(
                request,
                "encyclopedia/error.html",
                {
                    "error": 400,
                    "error_message": f"The title '{exists[0]}' already exists",
                },
            )
    return render(request, "encyclopedia/create.html")


def edit(request, entry:str):
    entry_content = util.get_entry(entry)
    if request.method == "POST":
        new_content = request.POST.get("textMarkdown").encode("utf-8")
        if new_content:
            util.save_entry(entry, new_content)
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[entry]))
        else:
            return render(request, "encyclopedia/error.html", {
                "error": 400,
                "error_message": "Markdown text can't be blank"
            })
    return render(request, "encyclopedia/edit.html", {"entry": entry, "entry_content": entry_content})


def random_page(request):
    entries = util.list_entries()
    entry = random.choice(entries)
    return HttpResponseRedirect(reverse("encyclopedia:entry", args=[entry]))

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new Page
{% endblock title %}

{% block body %}
    <div class="container">
        <form action="{% url 'encyclopedia:create' %}" method="POST">
            {% csrf_token %}
            <h2>Create a new Wiki Page</h2>
            <label>Title:</label>
            <input type="text" placeholder="Wiki Title" name="title" required>
            <textarea name="textarea" placeholder="Some Markdown Text" required></textarea>
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock body %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ entry }}
{% endblock title %}

{% block body %}
    <div class="container">
        <form action="{% url 'encyclopedia:edit' entry %}" method="POST">
            {% csrf_token %}
            <h2>Edit Wiki Page</h2>
            <label>Title: {{ entry }}</label>
            <textarea name="textMarkdown" placeholder="Some Markdown Text" required>{{ entry_content }}</textarea>
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock body %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_name }}
{% endblock %}

{% block body %}
    <div class="container">
        {% if entry %}
            <p>{{ entry|safe }}</p>
            <a href="{% url 'encyclopedia:edit' entry_name %}">Edit</a>
        {% else %}
            <p>404</p>
            <p>Page not found</p>
        {% endif %}
    </div>
{% endblock  %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ error }}
{% endblock title %}

{% block body %}
    <div class="container">
        <h1>{{ error }}</h1>
        <p>{{ error_message }}</p>
    </div>
{% endblock body %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="container">
        <h1>All Pages</h1>
        <ul class="list-group">
            {% for entry in entries %}
                <li class="list-group-item" style="background-color: #f0f0f0; list-style: none;"><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Wiki:{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit" style="visibility: hidden;">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock title %}

{% block body %}
<div class="container">
    <h1>Search Results</h1>
    <ul>
        {% if entry %}
            {% for en in entry %}
                <li><a href="{% url "encyclopedia:entry" en %}">{{ en }}</a></li>
            {% endfor %}
        {% else %}
            <h1>404</h1>
            <p>Enter some valid input</p>
        {% endif %}
    </ul>
</div>
{% endblock body %}